### ISSUE TITLE
Add credit notes showing error

### ISSUE THREAD

**Issue by antonym8** [antonym8/Selvi-Books#45]
[screen-capture (7).webm](https://github.com/antonym8/Selvi-Books/assets/142376069/5d66c6e8-7873-4aa5-bd29-569be5ee2529)

**Comment by gurum8** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed

![Screenshot (236)](https://github.com/antonym8/Selvi-Books/assets/142376069/37bc7260-22b0-4859-a1e0-774476f602eb)
